// test cases for the local fallback system

import assert from "node:assert/strict";
import test from "node:test";
import {detectSponsorSegments} from "../detector/detector.js";
import {parseTranscript} from "../detector/transcript.js";


function event(startSec, endSec, text) {
    return {startMs: startSec * 1000, endMs: endSec * 1000, text};
}

// https://www.youtube.com/watch?v=m5t08CREHcE
test("finds the complete CodeRabbit read from the supplied failure report", () => {
    const events = [
        event(218, 230, "arbitrary header injection from a privilege standpoint and the data is untrusted"),
        event(230, 234, "But the data on the outside is also evil. And guys, real quick before we keep going, I want to talk about today's video sponsor, Code Rabbit."),
        event(234, 247, "I know there's a lot of AI hype out there. With AI coming online every day, there are millions and millions of lines of code generated by AI models."),
        event(247, 264, "Code Rabbit is an AI code review tool that will look at your pull requests, reason about your code, and make actionable recommendations about security vulnerabilities."),
        event(264, 282, "All I have to do is provide an access token and then I can go into Code Rabbit and set up a personality or profile for how I want it to do reviews."),
        event(282, 300, "Code Rabbit identified some serious security vulnerabilities. If you don't want to wait until a pull request, the Code Rabbit CLI tool has you covered."),
        event(300, 310, "It integrates in all of your IDE apps like Claude, Codex, and Gemini. With Code Rabbit CLI, you can vibe code with confidence."),
        event(310, 314, "The best way to help the channel out is to go try the sponsor out. Go give Code Rabbit a shot on your repos. You can use Code Rabbit for free at the URL below."),
        event(314, 317, "Code Rabbit, thank you for sponsoring the video. Let's get back to it."),
        event(317, 329, "Okay, so they enabled large blobs. Who cares? There are other kinds of headers with weird side effects inside Git."),
        event(329, 345, "All this testing was occurring on GitHub Enterprise Server, a local version of GitHub that you can run to do testing."),
    ];

    assert.deepEqual(detectSponsorSegments(events), [{
        startMs: 230_000,
        endMs: 317_000,
        confidence: "high",
        reason: "explicit-boundary",
    }]);
});

// https://www.youtube.com/watch?v=2RyxyrwYh0M
test("detects a sponsor when ASR drops the possessive in this video's sponsor", () => {
    const events = [
        event(561, 568, "People who know him well point out that Shakespeare was illiterate. How was he sending those texts?"),
        event(568, 577, "The texts, though suspicious, are leading police nowhere. Months pass and the trail is getting cold."),
        event(577, 588, "The sheriff tells a reporter that they have no idea where Abraham Shakespeare is."),
        event(588, 597, "Perhaps Shakespeare simply does not want to be found. But this is nowhere near the truth."),
        event(597, 604, "And if it was not for everyday people on the internet, the truth may never have come to light."),
        event(604, 613, "If what you need isn't a team of internet sleuths, but a team of lawyers, then Morgan and Morgan, this video sponsor, has you covered."),
        event(613, 620, "If you are ever seriously hurt, your injury could be worth millions."),
        event(620, 629, "A Morgan and Morgan case in Florida ended in a settlement of 12 million dollars, 34 times the highest insurance offer."),
        event(629, 636, "Another case went home with 40 times the highest insurance offer at 26 million dollars."),
        event(636, 643, "They do not settle for lowball offers. If you become their client, they will fight to get you what you deserve."),
        event(643, 651, "You do not have to pay unless you win. If you get seriously injured, your case could be worth millions."),
        event(651, 658, "Start your claim now with Morgan andorggan at forthepeople.com/bw found in the description or by scanning the QR code on screen."),
        event(658, 666, "And thank you Morgan and for sponsoring today's video. On December 2nd, a user posts about the Shakespeare case."),
        event(666, 674, "The website investigates thefts, murders, and missing-person cases."),
    ];

    assert.deepEqual(detectSponsorSegments(events), [{
        startMs: 604_000,
        endMs: 666_000,
        confidence: "high",
        reason: "explicit-boundary",
    }]);
});

// https://www.youtube.com/watch?v=ax86iwfsfsE
test("detects the Test'em All dialogue read from its ASR-damaged sponsor assertion", () => {
    const events = [
        event(146, 153, "what's simple about cutting up someone's insides oh hey what did you get in here Grill since I heard you talking about Disneyland I thought maybe you were"),
        event(153, 161, "talking about bringing us both like you promised incorrect statement detected my audio data records reveal zero conversations that match this"),
        event(161, 169, "description you record our conversations I keep a documented record of many things including the countless hours you spend playing games on your phone if"),
        event(169, 177, "wasted potential were an energy source you'd solve the global crisis you should be using testal a Loyalty Rewards app for mobile games this video sponsor"),
        event(177, 185, "allows you to acquire monetary resources for playing your favorite games meaning you could generate something with this time other than regret hey wait you"),
        event(185, 192, "could get paid to play games how does it work even for you whose cognitive abilities are rivaled by a potato clock it is simple step one download testim"),
        event(192, 200, "all step two confirm access so your phone may track your progress step three choose from a list of all the top games to play and download it note that coin"),
        event(200, 208, "rewards may depend on the game chosen simple as that then testal tracks your progress and once you have acquired enough coins you may cash out via the"),
        event(208, 217, "rewards Tab and choose from a variety of options like PayPal Amazon and much more wow it is easy look at how many coins I got and I just got started look brw they"),
        event(217, 225, "got starbu you can acquire even more coins with weekend and daily promotions I use it daily and have utilized it to procure my monitoring equipment oh I"),
        event(225, 234, "mean coffee filters be sure to click the link below so you can download test them all or scan this QR code you see on the screen and start earning by playing your favorite games okay Howard cool app but"),
        event(234, 243, "quit deflecting did I make up Bru's promise to take me to Disneyland yes but did I have a consent to being recorded 24/7 no it is within Smart Home"),
        event(243, 251, "Appliance standard protocol unlike lying which seems to be within yours ah it was worth a try wa hey it's not gaslighting"),
    ];

    assert.deepEqual(detectSponsorSegments(events), [{
        startMs: 169_000,
        endMs: 234_000,
        confidence: "high",
        reason: "explicit-boundary",
    }]);
});


test("does not accept a dangling this-video-sponsor phrase without a commercial read", () => {
    assert.deepEqual(detectSponsorSegments([
        event(0, 8, "The credits list this video sponsor"),
        event(8, 16, "The next scene returns to the investigation and its timeline."),
        event(16, 24, "The witnesses then describe what happened at the school."),
    ]), []);
});

// https://www.youtube.com/watch?v=hMPrQyGJk3A
test("detects an undisclosed service ad from sustained commercial evidence", () => {
    const events = [
        event(806, 813, "Cart looks through the living room window and notices his mother speaking with police officers."),
        event(813, 820, "Panicking, he pauses the video, runs to his room, and locks the door."),
        event(820, 829, "Officers begin piecing things together. The boy could be tied to Sheila's murder."),
        event(829, 836, "Detectives will step inside to follow up on the lead, but what they find will defy their expectations."),
        event(836, 845, "But before we get to that, it is worth noting how much people are forced to carry: fear, trauma, and the day-to-day burden of surviving."),
        event(845, 853, "Sometimes that weight shows up in other ways, too, like debt. Do you feel crushed by debt?"),
        event(853, 860, "Those high-interest loans, that mountain of credit card debt, or overwhelming medical bills could be gone quicker than you think."),
        event(860, 869, "Imagine being debt-free, not in ten years, but in as little as just two years. You can finally feel free."),
        event(869, 877, "PDS Debt are experts at making this happen. They negotiate with the companies you owe so you can owe significantly less."),
        event(877, 884, "They listen to your unique situation to create a personalized plan that works regardless of your credit score."),
        event(884, 893, "They tackle credit cards, personal loans, collections, and medical bills."),
        event(893, 901, "Finding the right solution can save you money and get you debt-free faster, putting you back in control. Their results speak for themselves."),
        event(901, 907, "PDS Debt holds an A-plus Better Business Bureau rating and hundreds of five-star reviews."),
        event(907, 915, "They have helped tens of thousands of people break free of debt. Stop living in debt. Get your free assessment and find the best option for you."),
        event(915, 920, "Go right now to pdsd.com/inssanity."),
        event(920, 927, "You are just thirty seconds away from starting to get out of debt. That is pdsdebt.com/inssanity."),
        event(927, 938, "With that said, let's get back to the scene where detectives are about to go inside Rebecca's house."),
        event(938, 946, "Do you care if we come in? I do have two cats, though."),
    ];

    assert.deepEqual(detectSponsorSegments(events), [{
        startMs: 836_000,
        endMs: 927_000,
        confidence: "high",
        reason: "explicit-boundary",
    }]);
});


// https://www.youtube.com/watch?v=76fl_HngZXU
test("keeps an interleaved partner read open across brief content cutaways", () => {
    const events = [
        event(853, 860, "Does anybody have a second guess about what that prison slang might mean?"),
        event(860, 869, "A fish is supposed to be a newly incarcerated person. Like fresh fish."),
        event(869, 880, "One of you will get the opportunity to ask three questions to another contestant."),
        event(880, 900, "After this round, one person will be eliminated. Each of you will go to the confessional booth while they lock in their choices."),
        event(900, 909, "Let me show you the partner of today's video: Odoo."),
        event(910, 916, "I am questioning the big guy because he knows nothing about prison."),
        event(916, 924, "Whether you are trying to stay organized, save time, or make life easier, Odoo is the all-in-one solution to manage your business."),
        event(924, 926, "We might need it to help us keep track of these stories."),
        event(926, 939, "Who do you think gained credibility that round? Number one gave me a pretty deep story."),
        event(939, 943, "I wanted to target number four because I was not sure his story was accurate."),
        event(943, 953, "One of the best things about Odoo is that it helps with manual input, integration, complicated software, and overhead costs."),
        event(953, 963, "Odoo can solve this without switching systems. Everything is on one platform, and you choose the apps you need."),
        event(963, 973, "Whether you have a business or are starting one, it is a simple way to manage it, and Odoo makes it easy to scale."),
        event(973, 980, "I am targeting the guy in the bomber jacket. He looks like he belongs in Fast and Furious."),
        event(980, 988, "Odoo makes it easy to manage any business. For my YouTube channel I can set up production, planning, and scheduling."),
        event(988, 996, "It also has real-time inventory tracking. Click apps and add anything you need in one click."),
        event(996, 1005, "Let us add an expense tracker by clicking install. My team can upload receipts, and it only takes a couple of seconds."),
        event(1005, 1008, "I do not want to target anybody. This is silly."),
        event(1008, 1015, "If you want to support the channel, use the link in the description or scan the QR code to schedule a free consultation with an Odoo expert."),
        event(1015, 1017, "I think the contestants are coming back."),
        event(1017, 1024, "Let us see who they go after. I will pull a name from this container."),
    ];

    assert.deepEqual(detectSponsorSegments(events), [{
        startMs: 900_000,
        endMs: 1_015_000,
        confidence: "high",
        reason: "explicit-boundary",
    }]);
});

// https://www.youtube.com/watch?v=zvDHfVr99MU
test("detects a dialogue-style travel app sponsor with an ASR-damaged brand", () => {
    const events = [
        event(845, 852, "He found a parked plane at the airport even though he had never received formal flight training."),
        event(852, 861, "He did not even know how to sit in the cockpit properly, but he got comfortable."),
        event(861, 870, "All this talk about planes reminded me that I need to get everything ready for my international trip."),
        event(870, 877, "I am trying to find out whether the convention center has Wi-Fi. I do not want to get a SIM card because it is such a hassle."),
        event(877, 885, "Just acquire S. Who is that? Not whom, but what. It is this video's sponsor. It is a mobile phone application."),
        event(885, 893, "It ensures a perpetual internet connection when traveling, works with Android and iOS, and provides a full refund if the eSIM is incompatible."),
        event(893, 901, "I frequently make use of it. It provides affordable eSIM plans in more than 160 countries and regions."),
        event(901, 909, "An eSIM is an electronic version of a SIM card that avoids airport queues and counterfeit cards."),
        event(909, 916, "It avoids airport queues and counterfeit SIM cards. That sounds better than searching for regular Wi-Fi."),
        event(916, 925, "As a seasoned traveler, it has helped me countless times and connects my systems to the network immediately upon arrival."),
        event(925, 932, "For example, when I visit my brother in the United Kingdom, S connects me as soon as I arrive."),
        event(932, 939, "That sounds great, except I do not have time for hacking my phone."),
        event(939, 948, "No advanced programming is required. Step one: download the S application using this QR code."),
        event(948, 956, "Step two: explore plans and select the country. Step three: select your plan."),
        event(956, 963, "Follow the prompts to activate the eSIM. There is also chat support 24/7 if you require assistance."),
        event(963, 970, "Get an exclusive 15 percent discount on S eSIM data plans by downloading the app and using our code Brew at checkout."),
        event(970, 978, "That was easy. One less thing to worry about. That is my ride."),
        event(978, 985, "Unplug me and place my unit in the box for the delivery driver."),
        event(985, 992, "I left enough iced coffee in the fridge. Text me when you get in."),
        event(992, 1000, "Thanks to S. So how did this high-school dropout get access to the plane?"),
    ];

    const [segment] = detectSponsorSegments(events, {
        includeMetadata: true,
    });
    assert.equal(segment.startMs, 861_000);
    assert.equal(segment.endMs, 992_000);
    assert.equal(segment.reason, "explicit-boundary");
    assert.equal(segment.category, "paid-sponsor");
});

test("detects the supplied Odoo outro read after thanking members and patrons", () => {
    const events = [
        event(5176, 5182, "amount of it, and by recycling the CO2. Either way, though, I think that's about"),
        event(5182, 5187, "all I have to say about making air alcohol. But before I go, I feel like"),
        event(5187, 5193, "this is a good time to mention some of the other air related projects that I'm working on, like turning air into"),
        event(5193, 5200, "gasoline, air into a bomb, and air into diamond. On top of that, I should say"),
        event(5200, 5206, "that I'm getting pretty close to finishing some of the projects that I started years ago, like making magnets"),
        event(5206, 5212, "from scratch, spinning carbon nano tubes, and liquid helium. Also, I think"),
        event(5212, 5219, "it goes without saying that all of these projects are both extremely timeconuming and expensive. And this is why I'm very"),
        event(5219, 5225, "thankful for all of our amazing YouTube members and patrons and for our sponsors"),
        event(5225, 5230, "like ODO who make long projects like this possible. If you haven't already"),
        event(5230, 5237, "heard of ODO, it's basically an all-in-one platform that provides everything you need to run a business."),
        event(5237, 5244, "And they have a ton of intuitive apps for things like managing sales and tracking inventory. They also have a"),
        event(5244, 5250, "custom website builder, which is personally my favorite. And I actually use it all the time to make random"),
        event(5250, 5256, "websites for some of the projects that I work on. I even went ahead and made one"),
        event(5256, 5262, "for the air alcohol, which I was easily able to do in barely 20 minutes, and I"),
        event(5262, 5268, "think it turned out pretty well. Besides just making websites though, something else that I really like about ODO is"),
        event(5268, 5276, "that it can easily scale based on your needs and you don't have to immediately commit to a bunch of apps. In fact, you"),
        event(5276, 5284, "can actually just start with one app and then scale from there at your own pace, only adding more when you need them or"),
        event(5284, 5291, "even removing them if you stop needing them. All of this is also all available in just one simple interface with just"),
        event(5291, 5298, "one subscription, which I think is way better than having to subscribe to a bunch of different services."),
        event(5298, 5303, "But with that being said, I personally really like ODO. And whether you're"),
        event(5303, 5310, "looking to just build a website or whether you're looking for an all-in-one solution for your business, I definitely"),
        event(5310, 5318, "recommend checking them out right now. You can also try everything that ODU has to offer for free for 15 days with no"),
        event(5318, 5324, "credit card required. And you can get one app completely for free for life by"),
        event(5324, 5330, "simply going to the URL on screen or by clicking on the link in the description."),
        event(5330, 5335, "But yeah, I think that's about all I have to say. Uh, we've officially made"),
        event(5335, 5344, "it to the end of the longest video that I've ever made and I uh I guess I'll see"),
        event(5344, 5349, "you on the next one. As usual, a big thanks goes out to all"),
        event(5349, 5358, "of my supporters on YouTube and Patreon. Everyone who supports me can see all of my new videos at least 24 hours before I"),
    ];

    assert.deepEqual(detectSponsorSegments(events), [{
        startMs: 5_219_000,
        endMs: 5_330_000,
        confidence: "high",
        reason: "explicit-boundary",
    }]);
});

test("does not treat a plural sponsor acknowledgement as an ad by itself", () => {
    assert.deepEqual(detectSponsorSegments([
        event(0, 8, "We are thankful for our sponsors like Acme who make these projects possible."),
        event(8, 16, "The research team can now continue its long-running laboratory work."),
        event(16, 24, "Next, we will examine the latest results from the experiment."),
    ]), []);
});

test("does not backtrack a direct disclosure from one isolated setup phrase", () => {
    const events = [
        event(0, 8, "I am trying to find a replacement cable before the next recording."),
        event(8, 16, "This video is sponsored by Acme."),
        event(16, 24, "Visit acme.com and use our code TEST for 20 percent off."),
        event(24, 32, "Now let us get back to the video."),
    ];

    assert.deepEqual(detectSponsorSegments(events), [{
        startMs: 8_000,
        endMs: 32_000,
        confidence: "high",
        reason: "explicit-boundary",
    }]);
});

test("finds the complete CookUnity read from a structural sponsor disclosure", () => {
    const disclosures = [
        "choices. They’re the sponsor of this video. They dont have anything to do with me saying anything",
        "choices. They are, for this video, the sponsor. They dont have anything to do with me saying anything",
    ];

    for (const disclosure of disclosures) {
        const events = [
            event(1045, 1052, "Human cases have no standard clinical lab tests. Only a high-powered academic hospital"),
            event(1052, 1058.8, "with labs willing to look deeper would be able to do this. But when the results returned, they"),
            event(1058.8, 1065, "found out what it was. One angle of being healthy is eating well. Appropriate portion size and fresh"),
            event(1065, 1069, "nutritious food. And CookUnity is a great option for getting started on the right track for food"),
            event(1069, 1073.76, disclosure),
            event(1073.76, 1078, "about infectious disease. CookUnity is a chef collective that gets you restaurant quality meals"),
            event(1078, 1082, "by award-winning chefs delivered fresh to your door. Every week, I choose a couple of meals."),
            event(1082, 1087, "The system knows what I enjoyed and can make informed decisions for me."),
            event(1087, 1092, "Delivered to my door is a whole week of lunch that helps me stay on track."),
            event(1092, 1096, "These meals are amazing and there is a huge variety. Let me show you my favorites."),
            event(1096, 1101, "Roasted Chicken with Peruvian Sauce. The chicken is juicy and the sauce is amazing."),
            event(1101, 1106, "The flavors are incredibly unique. It is nutritionally very good too."),
            event(1106, 1112, "Take for example this Mexican Philly Cheesesteak Bowl With Smoky Baja Sauce."),
            event(1112, 1117.76, "It has a rich cheesy flavor. CookUnity is offering"),
            event(1117.76, 1121, "everyone watching this video 50 percent off their first order. Click the link in the description below and"),
            event(1121, 1127.68, "use my code CHUBBY50 to try it out. Link in the description with code CHUBBY50. I highly recommend"),
            event(1127.68, 1135, "it. In 1995 Japan, researchers were investigating the tick Ixodes persulcatus."),
            event(1135, 1140, "This is the tick that carries Borrelia burgdorferi and can cause Lyme disease."),
            event(1140, 1146, "Spirochetes have a body part that helps them twist through their environment."),
            event(1146, 1154, "Flagella rotate and help the organism move through tissue."),
            event(1154, 1163, "The researchers collected more ticks from the surrounding region."),
            event(1163, 1172, "They compared the samples and documented another unusual organism."),
            event(1172, 1181, "The investigation continued as they reviewed the laboratory findings."),
        ];

        const segments = detectSponsorSegments(events, {
            includeMetadata: true,
        });
        assert.equal(segments.length, 1, disclosure);
        assert.equal(segments[0].startMs, 1_058_800, disclosure);
        assert.equal(segments[0].endMs, 1_131_680, disclosure);
        assert.equal(segments[0].category, "paid-sponsor", disclosure);
    }
});

test("does not extend an explicit disclosure without later commercial evidence", () => {
    assert.deepEqual(detectSponsorSegments([
        event(0, 8, "They are, for this video, the sponsor."),
        event(8, 28, "Today we are examining the first group of laboratory samples."),
        event(28, 48, "The researchers recorded each result and checked it twice."),
        event(48, 68, "Next they compared the control group with the remaining cases."),
        event(68, 88, "The investigation continued with another set of measurements."),
    ]), [{
        startMs: 0,
        endMs: 12_000,
        confidence: "medium",
        reason: "explicit-start+low-evidence-timeout",
    }]);
});

test("anchors the complete Saily read at its spoken sponsor transition", () => {
    const segments = detectSponsorSegments([
        event(204, 214, "A propulsion system using fusion or antimatter could reach a substantial fraction of the speed of light."),
        event(214, 224, "We will optimistically assume a spaceship can fly at around twenty percent the speed of light."),
        event(224, 232, "Which is extremely fast, sixty thousand kilometers per second."),
        event(232, 239, "Fast enough to reach the edge of the solar system in just three and a half days."),
        event(239, 245, "Alpha Centauri, the closest star system to our own in twenty years. We can work with that."),
        event(245, 251, "There is only one small problem. We do not have internet. Wait, what?"),
        event(251, 261, "Just kidding, but our sponsor Saily can help you with that problem while travelling. Saily is the eSIM service app from the creators of NordVPN."),
        event(261, 269, "You can choose from affordable eSIM plans for over 200 destinations, so you will never be without an internet connection while traveling."),
        event(269, 278, "Just download the app, pick a data plan, use the code kurzgesagt for a 15 percent discount on your first data package, and install the eSIM."),
        event(278, 282, "It will activate automatically when you arrive, and you can start browsing right away."),
        event(282, 291, "You can also use Saily to feel like a local. It now comes with an app-based phone number."),
        event(291, 297, "Perfect for local apps and travel companions, and to keep your real number private."),
        event(297, 305, "With one app download, you have solved your internet problem, saving expensive roaming fees."),
        event(305, 312, "Download Saily and use the code kurzgesagt at checkout or go to saily.com/kurzgesagt."),
        event(312, 318, "Pick your next destination. We will go back to solving our trickier travel problems."),
        event(318, 332, "Everything should be sorted now, right? There is one issue: the barrier of dust."),
        event(332, 338, "Literally. Because while space is very empty, it is not actually empty."),
        event(338, 343, "There are energetic particles, gas, dust and things bigger than dust."),
        event(343, 350, "If you are going fast and smash into something, you have a huge problem."),
        event(350, 357, "At twenty percent the speed of light, this is true even if the thing is just an atom."),
        event(357, 366, "An iron atom that hits your spaceship has enough energy to carve a damage track."),
        event(366, 376, "The faster the ship moves, the more dangerous every collision becomes."),
        event(376, 386, "Even tiny particles release enormous energy when they strike the hull."),
    ], {includeMetadata: true});

    assert.equal(segments.length, 1);
    assert.equal(segments[0].startMs, 245_000);
    assert.equal(segments[0].endMs, 316_000);
    assert.equal(segments[0].confidence, "medium");
    assert.equal(segments[0].category, "paid-sponsor");
});


test("does not treat ordinary sponsor discussion as an advertisement", () => {
    const events = [
        event(0, 8, "GitHub Sponsors is a feature for funding open source maintainers."),
        event(8, 16, "A project can have several sponsors and different sponsorship tiers."),
        event(16, 24, "Now we will inspect how the API represents those relationships."),
    ];
    assert.deepEqual(detectSponsorSegments(events), []);

    assert.deepEqual(detectSponsorSegments([
        event(0, 8, "This video is about sponsors and how advertising disclosures work."),
        event(8, 16, "Sponsors appear throughout this video as examples for the lesson."),
        event(16, 24, "Now we will compare the wording used in each example."),
    ]), []);
});

test("does not skip a normal product review from one generic call to action", () => {
    const events = [
        event(40, 49, "This phone has the fastest processor in its class and I have been testing it all week."),
        event(49, 58, "You should check out the link in the description if you want the full specification sheet."),
        event(58, 68, "Now let's compare its camera with last year's model."),
    ];
    assert.deepEqual(detectSponsorSegments(events), []);
});

test("detects a commercial read without the literal word sponsor", () => {
    const events = [
        event(100, 108, "Before we continue, here is a quick word from Acme."),
        event(108, 119, "Head over to acme.com/alex and start your free trial today."),
        event(119, 132, "Use promo code ALEX for 20 percent off your first order."),
        event(132, 138, "Thanks to Acme for supporting the show. Now let's get back to the story."),
        event(138, 148, "The next stage of the experiment changes the pressure."),
    ];

    const [segment] = detectSponsorSegments(events);
    assert.equal(segment.startMs, 100_000);
    assert.equal(segment.endMs, 138_000);
    assert.equal(segment.confidence, "high");
});

// https://www.youtube.com/watch?v=7SRofyY-lRM
test("detects a sponsor introduced by thanking a brand for supporting the content", () => {
    const events = [
        event(236, 244, "The reviews could be written by bots or by people who received the game for free."),
        event(244, 251, "Because Windows allows dynamic loading, a game can load a malicious library and act as an info stealer."),
        event(251, 259, "If you accidentally run one of these and get your accounts hacked, I made a tutorial explaining what to do."),
        event(259, 267, "I still recommend watching that tutorial so you can stay calm and understand the steps."),
        event(267, 276, "I hope you found this video helpful and that it cleared up misconceptions about malware from Steam."),
        event(276, 284, "It really is possible to get your accounts hacked by malware distributed through a game. I hope this clears up the misconceptions people have."),
        event(284, 293, "They can get their accounts hacked. I also want to thank Flare for supporting"),
        event(293, 300, "a lot of our educational content. This is a really powerful platform that allows you to monitor the dark web and"),
        event(300, 307, "look into illicit networks like forum posts and ransom leaks to see whether your email has been mentioned"),
        event(307, 314, "in any of these posts. That can tell you if your account could potentially be hacked or your data might be sold on the dark web."),
        event(314, 321, "They can monitor your entire organization and tell you if there is an event. If any of your employees get hacked, you can get a"),
        event(321, 329, "heads up. You also get threat intelligence to stay on top of what is happening on the attacker side. If you are interested in exploring the dark web or"),
        event(329, 336, "keeping your account safe and monitored, do check out Flare using the link in the description. It could be critical in preventing a breach of your"),
        event(336, 345, "organization. But thank you all so much for watching this video till the end and do not forget to subscribe to the channel."),
        event(345, 353, "Everything in the world of cyber security. This is Leo, and as always, stay informed and stay secure."),
    ];

    assert.deepEqual(detectSponsorSegments(events), [{
        startMs: 284_000,
        endMs: 336_000,
        confidence: "high",
        reason: "explicit-boundary",
    }]);
});

// https://www.youtube.com/watch?v=8g6x9S9F9hs
test("backtracks an endorsement-style sponsor disclosure to its rhetorical lead-in", () => {
    const events = [
        event(315, 321, "Those pesos would be charged to your credit card using the tourist exchange rate."),
        event(321, 326, "Whether this still works on some websites is none of my business."),
        event(326, 334, "The videos discussing whether it is legal are all in German, so I do not know what to do with this information."),
        event(334, 339, "Happy shopping!"),
        event(341, 345, "So, if you're the kind of person who watches videos about things like this,"),
        event(345, 350, "you probably like learning so much that you even like learning"),
        event(350, 353, "about things that ultimately do not really matter or seem useful."),
        event(353, 357, "And maybe part of the reason is because it can be tough to independently learn things"),
        event(357, 362, "that do matter and are useful, but that's exactly why I like"),
        event(362, 365, "our sponsor, Brilliant, so much."),
        event(365, 375, "They have a fantastic catalog of well designed courses about important STEM subjects."),
        event(375, 385, "Brilliant breaks these topics into small bite-sized chunks so you can make meaningful progress."),
        event(385, 400, "It explains concepts through simple graphics and interactive challenges."),
        event(400, 414, "This structure allows anyone willing to try to learn subjects that might seem impossible."),
        event(414, 419, "Try everything Brilliant has to offer free for a full 30 days."),
        event(419, 423, "Visit brilliant.org/HAI or click the link in the description."),
        event(423, 428, "The first 200 of you will get 20 percent off an annual subscription."),
        event(428, 436, "Thank you to our sponsor. Back to the video."),
    ];

    assert.deepEqual(detectSponsorSegments(events), [{
        startMs: 341_000,
        endMs: 436_000,
        confidence: "high",
        reason: "explicit-boundary",
    }]);
});

test("does not backtrack a rhetorical non-commercial sponsor mention", () => {
    assert.deepEqual(detectSponsorSegments([
        event(0, 5, "If you're the kind of person who enjoys helping at school,"),
        event(5, 10, "maybe part of the reason is that you enjoy community projects."),
        event(10, 18, "That's exactly why I like our sponsor program at the university."),
        event(18, 26, "Students meet every Friday to organize the volunteer schedule."),
    ]), []);

    assert.deepEqual(detectSponsorSegments([
        event(0, 8, "Our sponsor Alice can help students organize the school project."),
        event(8, 16, "She meets the group every Friday in the university library."),
        event(16, 24, "The volunteers review the schedule and assign the remaining tasks."),
    ]), []);
});

// https://www.youtube.com/watch?v=7SRofyY-lRM
test("keeps overlapping ASR captions active through later sponsor evidence", () => {
    const events = [
        event(288.2, 293.16, "from Steam and get your accounts hacked."),
        event(290.28, 295.28, "Also want to thank Flare for supporting"),
        event(293.16, 297.44, "a lot of our educational content. This"),
        event(295.28, 299.84, "is a really powerful platform that"),
        event(297.44, 302.4, "allows you to monitor the dark web and"),
        event(299.84, 305.64, "look into illicit networks like forum"),
        event(302.4, 307.76, "posts, ransom leaks to see if your email"),
        event(305.64, 309.08, "for example has been mentioned in any of"),
        event(307.76, 310.8, "these posts and that can tell you if"),
        event(309.08, 312.56, "your account could potentially be hacked"),
        event(310.8, 314.76, "or your data might be being sold on the"),
        event(312.56, 317.96, "dark web. They can actually monitor your"),
        event(314.76, 319.52, "entire organization and tell you if"),
        event(317.96, 321.36, "there is an event, if any of your"),
        event(319.52, 323.36, "employees get hacked, you can get a"),
        event(321.36, 325.4, "heads up. You also get a lot of threat"),
        event(323.36, 326.919, "intel to stay on top of what is happening"),
        event(325.4, 329.04, "on the attacker side. So, if you are"),
        event(326.919, 330.68, "interested in exploring the dark web or"),
        event(329.04, 332.76, "keeping your accounts safe and"),
        event(330.68, 334.919, "monitored, do check out Flare using link"),
        event(332.76, 336.64, "in description. It could be critical in"),
        event(334.919, 339.28, "helping you preventing a breach of your"),
        event(336.64, 341.72, "organization. But thank you all so much"),
        event(339.28, 343.52, "for watching this video till the end and"),
        event(341.72, 345.2, "do not forget to subscribe to the PC"),
        event(343.52, 346.8, "security channel to stay on top of"),
    ];

    assert.deepEqual(detectSponsorSegments(events), [{
        startMs: 288_200,
        endMs: 336_640,
        confidence: "high",
        reason: "explicit-boundary",
    }]);
});

test("does not treat a creator thanking their audience for support as a sponsor", () => {
    const events = [
        event(80, 89, "Thank you all for supporting the channel and helping us reach one million subscribers."),
        event(89, 98, "I appreciate every one of you, and now we can begin today's tutorial."),
        event(98, 107, "Open the settings page and select the display tab."),
    ];

    assert.deepEqual(detectSponsorSegments(events), []);
});

// some judelow video i lowkey forgot which one
test("keeps a feature-heavy NordVPN read as one complete segment", () => {
    const segments = detectSponsorSegments([
        event(542, 553, "This loss of communication had nothing to do with what subsequently happened."),
        event(553, 562, "Now when we are on the subject of theories, my team and I have seen a massive increase in AI-generated accident reports,"),
        event(562, 573, "falsified records and phishing sites, making our research both harder and more risky."),
        event(573, 583, "I have actually almost clicked and entered my details into sites like that, but here is where today's sponsor, NordVPN, steps in."),
        event(583, 593, "Nord is the fastest and most privacy-focused VPN out there and the only one certified by independent cybersecurity experts."),
        event(593, 606, "Their Threat Protection feature stopped millions of phishing attempts and it works by scanning every website before it loads, checking for threats."),
        event(606, 615, "If it finds something fishy, it will instantly block access to that site before any real damage is done."),
        event(615, 627, "I absolutely love this feature because it protects my privacy by stopping trackers and spam."),
        event(627, 637, "Head over to nordvpn.com/pilot or scan this QR code."),
        event(637, 649, "You get four extra months free with a two-year plan and a 30-day money back guarantee."),
        event(649, 653, "Thank you so much, Nord. Now back to the video."),
        event(653, 660, "Once communication was sorted out, the rest of the climb proceeded uneventfully."),
    ]);

    assert.deepEqual(segments, [{
        startMs: 553_000,
        endMs: 653_000,
        confidence: "high",
        reason: "explicit-boundary",
    }]);
});

test("detects the fragmented War Thunder sponsor read", () => {
    const events = [
        event(319.2, 323.52, "But before I trap a bunch of YouTubers,"),
        event(321.6, 325.12, "I got to tell you about today's sponsor."),
        event(323.52, 327.44, "Thank you to War Thunder for sponsoring"),
        event(325.12, 329.36, "the video. War Thunder is an incredibly"),
        event(327.44, 331.36, "realistic free-to-play multiplayer"),
        event(329.36, 333.2, "military action game where aircraft,"),
        event(331.36, 335.2, "naval, and ground vehicles fight in dynamic"),
        event(335.2, 339.2, "battles at locations around the world."),
        event(339.2, 343.2, "All the vehicles look exactly like they do"),
        event(343.2, 347.2, "in real life and behave the same way."),
        event(347.2, 350.56, "The graphics, physics, and sound in War"),
        event(350.56, 353.68, "Thunder are constantly improving. So,"),
        event(353.68, 357.68, "the game looks stunning and allows players"),
        event(357.68, 361.68, "to immerse themselves in a real war."),
        event(361.68, 365.68, "They recently released new vehicles."),
        event(365.68, 369.759, "And they are even adding infantry."),
        event(369.759, 374.56, "Please download War Thunder for free on"),
        event(372.0, 376.0, "PC, Xbox, or PlayStation by using the"),
        event(374.56, 378.479, "link in the description. If you're a new"),
        event(376.56, 380.479, "player or you haven't played War Thunder"),
        event(380.479, 384.4, "in more than six months, you'll receive rewards."),
        event(384.4, 388.4, "You can also immerse yourself in exciting"),
        event(386.88, 390.72, "battles in War Thunder Mobile,"),
        event(390.72, 394.16, "Download it and play it for free on iOS"),
        event(392.72, 396.16, "or Android using the link in the"),
        event(394.16, 398.639, "description. All right, back to the"),
        event(396.16, 400.319, "video. Let's go trap some players. Now"),
        event(400.319, 404.319, "that the trap was done, we baited players over."),
    ];

    const segments = detectSponsorSegments(events, {includeMetadata: true});

    assert.equal(segments.length, 1);
    assert.equal(segments[0].startMs, 319_200);
    assert.equal(segments[0].endMs, 400_319);
    assert.equal(segments[0].category, "paid-sponsor");
    assert.equal(segments[0].confidence, "high");
    assert.equal(segments[0].reason, "explicit-boundary");
});

// https://www.youtube.com/watch?v=3oswJT0vBPM&t=706s
test("backtracks the Pine Hosting read to its introductory transition", () => {
    const events = [
        event(273, 283, "Oh my god. There's so many. Unfortunately, I got hit into the trip wire."),
        event(283, 293, "So I triggered it on myself and the two people behind me."),
        event(293, 303, "That's four points for ChatGPT and I headed into game two. But before I trap these guys, hello Pine Hosting."),
        event(303, 312, "Pine Hosting is the best server provider out there. If you want to make a server with your friends, you may as well use them."),
        event(312, 319, "Click the link in the description or the pinned comment to get to their website and use code Jude at checkout for 30 percent off."),
        event(319, 327, "Their servers are fast, affordable, and super easy to use and set up."),
        event(327, 336, "A server only takes about five minutes to set up, and you can add mods with one click."),
        event(336, 345, "They also offer hosting on other games like Rust. I had a server with Pine and it ran smoothly."),
        event(345, 352, "I also use Pine Hosting for my Minecraft server, Goober SMP, and it is not laggy."),
        event(352, 361, "Use code Jude. It helps me and gives you 30 percent off. Thank you again to sponsoring this video, Mr. Pine Hosting."),
        event(361, 371, "Here's the bread. I ran out of sprint. I'll bait them and you run past it."),
    ];

    assert.deepEqual(detectSponsorSegments(events), [{
        startMs: 293_000,
        endMs: 361_000,
        confidence: "high",
        reason: "explicit-boundary",
    }]);
});

test("does not treat crime-story language as a gambling promotion", () => {
    const events = [
        event(1658, 1665, "Attempting to sell stolen securities carried up to 20 years. Money laundering added another 20."),
        event(1665, 1673, "He was looking at potentially spending the rest of his life in federal prison."),
        event(1673, 1681, "FBI agents laid out his two options. Cooperate or go to trial. If he cooperated, he provided them names."),
        event(1678, 1686, "His two options were cooperate or go to trial. If he cooperated, he provided them names and details."),
        event(1681, 1689, "He might get a reduced sentence, maybe five years instead of twenty or thirty."),
        event(1699, 1708, "Osborne did not have to think long. He had a gambling problem, not a death wish."),
        event(1702, 1710.72, "He had a gambling problem, not a death wish. Osborne became a cooperating witness."),
        event(1708, 1716, "He explained how Keith Cheeseman contacted him and how the bonds were delivered."),
    ];

    assert.deepEqual(detectSponsorSegments(events), []);
});

// https://www.youtube.com/watch?v=YcRpG6IVmzo
test("detects the complete merch self-promotion from its spoken introduction", () => {
    const events = [
        event(2498, 2509, "And somewhere 135 million pounds in ghost bonds might still be out there, if they ever existed at all."),
        event(2509, 2511, "Can I do the merch now? Go for it, Grill."),
        event(2511, 2518, "Hey, you. Do you want to support this channel and look good doing it?"),
        event(2518, 2527, "Some shirts for you. Merch alert. Brew merch is finally here."),
        event(2527, 2565, "First up is a man who needs no introduction. He is repping the catchphrase from this channel."),
        event(2565, 2615, "Next we have more shirts and a crew neck sweater guaranteed to keep you cozy."),
        event(2615, 2635, "People are going to buy that. And last is the Clankers cannot create shirt."),
        event(2635, 2643, "Go on over to shop.brewsolves.com."),
        event(2643, 2651, "Check your DMs at stack.com/bw to get your secret code."),
        event(2651, 2660, "Use the code to get 15 percent off your merch order at checkout."),
        event(2660, 2669, "Order now because once this merch drop is gone, it is gone. Link in the description."),
        event(2669, 2679, "Now back to you, Brew. Hit the like button and subscribe to our channel."),
    ];

    const segments = detectSponsorSegments(events, {includeMetadata: true});
    assert.equal(segments.length, 1);
    assert.equal(segments[0].startMs, 2_509_000);
    assert.equal(segments[0].endMs, 2_679_000);
    assert.equal(segments[0].category, "self-promotion");
    assert.equal(segments[0].confidence, "high");
    assert.equal(segments[0].reason, "explicit-boundary");
});


test("requires corroboration for contextual sponsor introductions", () => {
    const contextualPhrases = [
        "This research project was made possible by community volunteers.",
        "They reached out to me after reading my report about the experiment.",
        "I want to thank Alice for supporting this research project.",
        "Our friends at school helped us assemble the robot.",
        "We partnered with the university to publish the research.",
        "This conference is presented by the university history department.",
        "Before we continue, a quick word from our teacher about the assignment.",
        "But before we get to that, consider why people feel overwhelmed by debt.",
        "The tournament was sponsored by Acme several years ago.",
    ];

    for (const phrase of contextualPhrases) {
        assert.deepEqual(detectSponsorSegments([
            event(0, 8, phrase),
            event(8, 16, "We collected the measurements and checked every result twice."),
            event(16, 24, "Next, we will compare the control and experimental groups."),
        ]), [], phrase);
    }
});

test("rejects quoted and historical sponsor discussion", () => {
    assert.deepEqual(detectSponsorSegments([
        event(0, 8, "The presenter kept saying this video is sponsored by Acme as an example."),
        event(8, 16, "The lesson explains how advertising disclosures are written."),
        event(16, 24, "Now we will rewrite the sentence in neutral language."),
    ]), []);

    assert.deepEqual(detectSponsorSegments([
        event(0, 8, "This video was sponsored by Acme in 2018, before the company closed."),
        event(8, 16, "We are documenting the history of old online advertising campaigns."),
        event(16, 24, "The archive contains several other examples from that period."),
    ]), []);
});

test("does not mistake programming instructions for a promo read", () => {
    assert.deepEqual(detectSponsorSegments([
        event(0, 8, "Use code TEST in the configuration file to select the test environment."),
        event(8, 16, "The link in the description points to the documentation for this example."),
        event(16, 24, "Check out the docs before running the program."),
        event(24, 32, "Now execute the script and inspect the terminal output."),
    ]), []);
});

test("finalizes an unfinished self-promotion at its last evidence", () => {
    const segments = detectSponsorSegments([
        event(0, 8, "Merch alert. Check out my merch in the channel store."),
        event(8, 20, "Today we are rebuilding the machine from the ground up."),
        event(20, 40, "First, remove the old panel and label every cable."),
        event(40, 60, "The replacement part fits into the same mounting holes."),
    ], {includeMetadata: true});

    assert.equal(segments.length, 1);
    assert.equal(segments[0].startMs, 0);
    assert.equal(segments[0].endMs, 12_000);
    assert.equal(segments[0].category, "self-promotion");
});

test("does not let a later sponsor start contaminate an ended candidate", () => {
    const segments = detectSponsorSegments([
        event(0, 8, "Merch alert. Check out my merch in the channel store."),
        event(8, 20, "Today we are rebuilding the machine from the ground up."),
        event(20, 40, "First, remove the old panel and label every cable."),
        event(40, 48, "This video is sponsored by Acme."),
        event(48, 56, "Visit acme.ai and start your free trial today."),
        event(56, 64, "Thanks to our sponsor. Back to the video."),
    ], {includeMetadata: true});

    assert.deepEqual(segments.map(segment => ({
        startMs: segment.startMs,
        endMs: segment.endMs,
        category: segment.category,
    })), [
        {startMs: 0, endMs: 12_000, category: "self-promotion"},
        {startMs: 40_000, endMs: 64_000, category: "paid-sponsor"},
    ]);
});

test("uses the latest matching span when an outro overlaps sponsor audio", () => {
    const segments = detectSponsorSegments([
        event(0, 8, "This video is sponsored by Acme."),
        event(8, 16, "Visit acme.ai and start your free trial today."),
        event(16, 20, "The service helps you protect your accounts."),
        event(20, 24, "It also saves time when reviewing alerts."),
        event(22, 25, "But thank you all so much"),
        event(24, 28, "for watching this video."),
    ]);

    assert.deepEqual(segments, [{
        startMs: 0,
        endMs: 22_000,
        confidence: "high",
        reason: "explicit-boundary",
    }]);
});

test("is invariant to equivalent input ordering at equal timestamps", () => {
    const opening = event(0, 8, "This video is sponsored by Acme.");
    const tiedEvents = [
        event(8, 16, "Visit acme.ai and start your free trial today."),
        event(8, 16, "Use promo code SAVE for 20 percent off."),
        event(8, 16, "The service helps you review every alert."),
    ];
    const closing = event(
        16,
        24,
        "Thanks to our sponsor. Back to the video.",
    );
    const permutations = [
        [0, 1, 2],
        [0, 2, 1],
        [1, 0, 2],
        [1, 2, 0],
        [2, 0, 1],
        [2, 1, 0],
    ];
    const expected = detectSponsorSegments(
        [opening, ...tiedEvents, closing],
        {includeMetadata: true},
    );

    for (const order of permutations) {
        assert.deepEqual(
            detectSponsorSegments([
                opening,
                ...order.map(index => tiedEvents[index]),
                closing,
            ], {includeMetadata: true}),
            expected,
        );
    }
});

test("recognizes current sponsor domains beyond the original TLD list", () => {
    const [segment] = detectSponsorSegments([
        event(0, 8, "This video is sponsored by Cursor."),
        event(8, 16, "Visit cursor.ai and start your free trial today."),
        event(16, 24, "Thanks to our sponsor. Back to the video."),
    ], {includeMetadata: true});

    assert.ok(segment.groups.includes("url"));
});

test("parses YouTube json3 transcript events", () => {
    const parsed = parseTranscript(JSON.stringify({
        events: [
            {tStartMs: 1_000, dDurationMs: 2_000, segs: [{utf8: "hello "}, {utf8: "world"}]},
            {tStartMs: 3_000, dDurationMs: 1_500},
        ],
    }));

    assert.deepEqual(parsed, [{
        startMs: 1_000,
        endMs: 3_000,
        text: "hello world",
    }]);
});
